openapi: 3.0.0
info:
  title: Quiz API
  version: 1.0.0
  description: API dla aplikacji quizowej

servers:
  - url: http://localhost:5000/api
    description: Serwer lokalny

tags:
  - name: Authorization
    description: Operacje związane z autoryzacją
  - name: Quiz
    description: Operacje związane z quizem
  - name: Questions
    description: Operacje związane z pytaniami

paths:
  /auth/register:
    post:
      tags:
        - Authorization
      summary: Rejestracja nowego użytkownika
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  format: name
                  example: "test"
                email:
                  type: string
                  format: email
                  example: "test@example.com"
                password:
                  type: string
                  format: password
                  example: "Password123@"
                confirmPassword:
                  type: string
                  format: password
                  example: "Password123@"
              required:
                - name
                - email
                - password
                - confirmPassword
      responses:
        "201":
          description: Użytkownik został pomyślnie zarejestrowany
        "400":
          description: Nieprawidłowe dane wejściowe
        "409":
          description: Użytkownik o podanym adresie email już istnieje

  /auth/login:
    post:
      tags:
        - Authorization
      summary: Logowanie użytkownika
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                  example: "test@example.com"
                password:
                  type: string
                  format: password
                  example: "Password123@"
              required:
                - email
                - password
      responses:
        "200":
          description: Użytkownik zalogowany pomyślnie
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  userData:
                    type: object
                    properties:
                      login:
                        type: string
                        type: name
                      id:
                        type: string
                  accessToken:
                    type: string
                  refreshToken:
                    type: string
        "401":
          description: Nieprawidłowe dane logowania

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
